# Generated by Django 5.2.18 on 2026-10-08 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo_o_equipo', models.CharField(max_length=100)),
                ('descripcion_falla', models.TextField()),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ingresado', 'Ingresado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('entregado', 'Entregado')], default='ingresado', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_mano_obra', models.IntegerField(default=0)),
                ('monto_repuestos', models.IntegerField(default=0)),
                ('monto_total', models.IntegerField(default=0)),
                ('reparacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MainApp.reparacion')),
            ],
        ),
    ]
